version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.15
executors:
  build_environment:
    docker:
      - image: circleci/buildpack-deps:buster

  deploy_environment:
    docker:
      - image: circleci/ruby:2.6

commands:
  bundle_source:
    steps:
      - run:
          name: "Bundle source code"
          command: |
              SOURCE_BUNDLE="$(git rev-parse HEAD)-$(date +%s).zip" && \
              echo "export SOURCE_BUNDLE=$SOURCE_BUNDLE" >> $BASH_ENV && \
              git archive -o $SOURCE_BUNDLE --format=zip HEAD

jobs:
  build:
    executor:
      name: build_environment

    working_directory: ~/build_freeswitch

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Image
          command: |
              docker build -t somleng/somleng-freeswitch .

      - run:
          name: Check Version
          command: |
              docker run --rm somleng/somleng-freeswitch /usr/bin/freeswitch -version

      - run:
          name: Push Image
          command: |
              if [ "$CIRCLE_BRANCH" = "upgrade_freeswitch" ]; then
                  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
                  docker build -t somleng/somleng-freeswitch:latest "$CIRCLE_REPOSITORY_URL#$CIRCLE_BRANCH"
                  docker push somleng/somleng-freeswitch
              fi

  deploy_production:
    executor:
      name: deploy_environment
    working_directory: ~/deploy_freeswitch
    steps:
      - aws-cli/install
      - aws-cli/configure
      - run:
          name: Assume Role
          command: |
              deploy_role=$(aws sts assume-role --role-arn "$AWS_DEPLOY_ROLE_ARN" --role-session-name "Deploy") && \
              echo "export DEPLOY_ACCESS_KEY_ID='$(echo $deploy_role | jq .Credentials.AccessKeyId | xargs)'" >> $BASH_ENV && \
              echo "export DEPLOY_SECRET_ACCESS_KEY='$(echo $deploy_role | jq .Credentials.SecretAccessKey | xargs)'" >> $BASH_ENV && \
              echo "export DEPLOY_SESSION_TOKEN='$(echo $deploy_role | jq .Credentials.SessionToken | xargs)'" >> $BASH_ENV

      - checkout
      - bundle_source

      - run:
          name: Deploy Production
          command: |
              ./.circleci/deploy/eb_deploy create_app_version -a somleng-freeswitch -b $AWS_DEPLOY_BUCKET_NAME -c $CIRCLE_SHA1 -s $SOURCE_BUNDLE --access-key-id "$DEPLOY_ACCESS_KEY_ID" --secret-access-key "$DEPLOY_SECRET_ACCESS_KEY" --session-token "$DEPLOY_SESSION_TOKEN"
              ./.circleci/deploy/eb_deploy -s $SOURCE_BUNDLE -e somleng-freeswitch-webserver  --access-key-id "$DEPLOY_ACCESS_KEY_ID" --secret-access-key "$DEPLOY_SECRET_ACCESS_KEY" --session-token "$DEPLOY_SESSION_TOKEN"
              ./.circleci/deploy/eb_deploy -s $SOURCE_BUNDLE -e somleng-freeswitch-simulator-webserver --access-key-id "$DEPLOY_ACCESS_KEY_ID" --secret-access-key "$DEPLOY_SECRET_ACCESS_KEY" --session-token "$DEPLOY_SESSION_TOKEN"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: Somleng
      - deploy_production:
          context: Somleng
          requires:
            - build
          filters:
            branches:
              only: upgrade_freeswitch
